# Generated by Django 4.2.1 on 2023-05-06 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pybo", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answer", old_name="create_table", new_name="create_date",
        ),
        migrations.RenameField(
            model_name="question", old_name="create_table", new_name="create_date",
        ),
    ]
